Abstract importnames
si-23/py-import-cycles pull request #25
Opened 2022-08-22 10:23 UTC by si-23

2022-08-23 08:50 UTC, Synss approved these changes

2022-08-23 09:33 UTC, Synss requested changes

2022-08-23 09:33 UTC, Synss commented on py_import_cycles/main.py
> +        return self._name == other._name
I think
```
ModuleName("a", "b", "c") == "a.b.c"
ModuleName("a", "b", "c") == ("a", "b", "c")
ModuleName("a.b", "c") == ModuleName("a.b.c")
ModuleName("a.b", "c") == ModuleName("a", "b", "c")
```
could be equal as well.

2022-08-23 09:33 UTC, Synss commented on py_import_cycles/main.py
> +    def joinname(self, name: str) -> ModuleName:
`relative_to` may be useful as well.

I think one way to canonicalize this `ModuleName` should be required and that would be `Path.resolve()` in pathlib.

2022-08-23 09:33 UTC, Synss commented on py_import_cycles/main.py
> +    parts = list(module_name.parts)
This is reverting to `List[str]` to make the new abstraction class useful. I would rather extend the implementation of the class to handle, at least, simple things such as appending/prepending. `pathlib.Path` does that using operator overloading `Path("x") / "y"`. That would be an idea here as well.

2022-08-23 09:33 UTC, Synss commented on py_import_cycles/main.py
> +            return ModuleName(import_from_stmt.module if import_from_stmt.module else "")
That may indeed create a `ModuleName("")` that, I believe, raises IndexError in a few cases as mentioned above.

Here again, we really need unit tests.

2022-08-23 09:33 UTC, Synss commented on py_import_cycles/main.py
> +        if self._is_builtin_or_stdlib(module_name.name):
`is_builtin_or_stdlib` could be defined on `ModuleName` as well.

At least, I believe it should be a free function (or two, one for builtin and one for stdlib).

2022-08-23 09:33 UTC, Synss commented on py_import_cycles/main.py
> +    def _get_name_prefix(self, import_from_stmt: ast.ImportFrom) -> ModuleName:
should most likely be a free function

2022-08-23 09:45 UTC, Synss requested changes

2022-08-23 09:45 UTC, Synss commented on py_import_cycles/main.py
> +    def from_name(self, module_name: ModuleName) -> None | Module:
It seems to me `from_name()` and `from_path()` do not have much to do with one another. I also find the name confusing. I would expect a `from_` function would be an alternative constructor such as
```
class K:
    @classmethod
    def from_x(cls, x: X) -> K:
        ...
```
there are example of this pattern in the stdlib as well.

Before this patch, both functions would return `Module` and now, one returns `Module | None` and the other `RegularPackage | PyModule`.

I think I do not understand this part of the code.

2022-08-23 09:45 UTC, Synss commented on py_import_cycles/main.py
> +    def _get_module(self, module_name: ModuleName) -> None | Module:
more common is, I believe, `Module | None`. `Module` is the important type. That is also what `pyupgrade` does.

2022-08-23 10:21 UTC, si-23 commented
Thx for your comments which are very useful and convincing.

2022-09-05 09:40 UTC, Synss approved these changes

2022-09-05 09:42 UTC, Synss approved these changes

2022-09-05 09:44 UTC, Synss approved these changes

2022-09-05 09:59 UTC, merged